#pragma once

#include "option.h"
#include "simulation_config.h"
#include <Eigen/Dense>
#include <vector>
#include <cmath>

/**
 * @class EuropeanPricer
 * @brief Computes European option prices from pre-simulated asset paths.
 *
 * This pricer assumes that `asset_paths_` contains `config_.num_paths` simulation
 * matrices. Each matrix has `config_.num_assets` rows and `config_.num_steps + 1`
 * columns (including the initial time t=0 column). The pricer computes the payoff
 * at maturity for each asset across all paths, averages the payoffs, and applies
 * discounting to return the present value.
 *
 * Notes:
 * - The pricer returns a vector of size `config_.num_assets` containing the price
 *   for each asset in the basket for the given strike and option type (call/put).
 * - Payoffs are computed elementwise for each asset (no cross-asset payoffs).
 */
class EuropeanPricer {
private:
    const SimulationConfig& config_;
    const std::vector<Eigen::MatrixXd>& asset_paths_;

public:
    /**
     * @brief Constructs a EuropeanPricer.
     * @param cfg Reference to the simulation configuration. Must outlive this object.
     * @param paths Reference to the vector of asset path matrices generated by the simulator.
     *
     * The constructor stores references; no copying of large path data is performed.
     */
    EuropeanPricer(const SimulationConfig& cfg, const std::vector<Eigen::MatrixXd>& paths)
        : config_(cfg), asset_paths_(paths) {
    }

    /**
     * @brief Prices a European option for each asset in the basket.
     *
     * For each simulated path p, this method reads the terminal asset prices
     * at time index `config_.num_steps` and computes the payoff:
     *   - Call:  max(S_T - strike, 0)
     *   - Put :  max(strike - S_T, 0)
     *
     * The method averages the payoffs across all paths and discounts the result
     * back to present value using the continuously compounded risk-free rate.
     *
     * @param strike Strike price of the option.
     * @param is_call If true price a call; otherwise price a put.
     * @return Eigen::VectorXd of length `config_.num_assets` containing the present
     *         value prices for each asset.
     */
    Eigen::VectorXd price(double strike, bool is_call) const {
        Eigen::VectorXd option_prices = Eigen::VectorXd::Zero(config_.num_assets);
        double t = config_.num_steps * config_.dt;
        double discount_factor = std::exp(-config_.risk_free_rate * t);

        for (int p = 0; p < config_.num_paths; ++p) {
            Eigen::VectorXd s_t = asset_paths_[p].col(config_.num_steps);

            Eigen::VectorXd payoffs(config_.num_assets);
            if (is_call) {
                payoffs = (s_t.array() - strike).cwiseMax(0.0).matrix();
            } else {
                payoffs = (strike - s_t.array()).cwiseMax(0.0).matrix();
            }

            option_prices += payoffs;
        }

        return (option_prices / static_cast<double>(config_.num_paths)) * discount_factor;
    }
};

/**
 * @class AmericanPricer
 * @brief Evaluates Amesican option premiums across simulated Monte Carlo paths
 * utilizing the Longstaff-Schwartz Least-Squares (LSM) backward induction algorithm.
 */
template <typename OptionType>
class AmericanPricer {
private:
    const SimulationConfig& config_;
    const std::vector<Eigen::MatrixXd>& asset_paths_;

    /**
     * @brief Generates a stable polynomial basis using a log-transformation.
     * @param s The stock price scalar at the current node.
     * @param k The strike price of the option (used to center the money-ness).
     * @return Eigen::VectorXd containing a 4-term log-polynomial basis.
     */
    Eigen::VectorXd evaluate_basis(double s, double k = 100.0) const {
        // Log-transformation compresses extreme right-tail outliers,
        // perfectly stabilizing the Eigen matrix condition number.
        double x = std::log(s / k);

        Eigen::VectorXd basis(4);
        basis(0) = 1.0;
        basis(1) = x;
        basis(2) = x * x;
        basis(3) = std::pow(x, 3);

        return basis;
    }

public:
    AmericanPricer(const SimulationConfig& cfg, const std::vector<Eigen::MatrixXd>& paths)
        : config_(cfg), asset_paths_(paths) {
    }

    /**
     * @brief Prices the American option independently for a specific asset index in the basket.
     * @param asset_idx The row index corresponding to the target stock (e.g., 0 for the first asset).
     * @param opt The templated American option contract containing the payoff structure.
     * @return The fair-value American option premium today (t=0).
     */
    double price_asset_option(int asset_idx, const OptionType& opt) const {
        int num_paths = config_.num_paths;
        int num_steps = config_.num_steps;
        double discount_factor = std::exp(-config_.risk_free_rate * config_.dt);

        // 1. Initialize the Cash Flow vector at Maturity (T)
        Eigen::VectorXd cash_flows(num_paths);
        for (int p = 0; p < num_paths; ++p) {
            double s_T = asset_paths_[p](asset_idx, num_steps);
            cash_flows(p) = opt.payoff(s_T);
        }

        // 2. Roll backward through time (T-1 down to 1)
        for (int t = num_steps - 1; t >= 1; --t) {

            // Discount future cash flows back to the current step t
            cash_flows *= discount_factor;

            std::vector<int> itm_paths;
            itm_paths.reserve(num_paths);

            // 3. Identify paths that are currently In-The-Money (ITM)
            for (int p = 0; p < num_paths; ++p) {
                double s_t = asset_paths_[p](asset_idx, t);
                if (opt.payoff(s_t) > 0.0) {
                    itm_paths.push_back(p);
                }
            }

            int num_itm = static_cast<int>(itm_paths.size());

            // If there are too few ITM paths to run a reliable regression, skip to the next step
            if (num_itm < 3) {
                continue;
            }

            // 4. Construct Design Matrix (A) and Target Vector (Y) for ITM paths
            Eigen::MatrixXd mat_a(num_itm, 4);
            Eigen::VectorXd vec_y(num_itm);

            for (int i = 0; i < num_itm; ++i) {
                int p_idx = itm_paths[i];
                double s_t = asset_paths_[p_idx](asset_idx, t);

                mat_a.row(i) = evaluate_basis(s_t);
                vec_y(i) = cash_flows(p_idx); // The discounted future cash flow for this path
            }

            // 5. Execute Least Squares Regression (A * beta = Y) via Rank-Revealing QR decomposition
            Eigen::VectorXd beta = mat_a.colPivHouseholderQr().solve(vec_y);

            // 6. Evaluate the Early Exercise Condition
            for (int i = 0; i < num_itm; ++i) {
                int p_idx = itm_paths[i];
                double s_t = asset_paths_[p_idx](asset_idx, t);

                double immediate_exercise = opt.payoff(s_t);
                double continuation_value = evaluate_basis(s_t).dot(beta);

                // If early exercise is optimal, mathematically "forget" future cash flows by overwriting
                if (immediate_exercise > continuation_value) {
                    cash_flows(p_idx) = immediate_exercise;
                }
            }
        }

        // 7. Discount the final cash flows from t=1 back to t=0 and average
        cash_flows *= discount_factor;
        return cash_flows.mean();
    }
};